# Option-1 : Createting docker image using command module
---
- hosts: ansible
  become: true

  tasks:
    - name: create docker image
      command: docker build -t regapp:latest .
      args:
        chdir: /opt/docker

    - name: create tag to push image onto dockerhub
      command: docker tag regapp:latest krisvu/regapp:latest

    - name: push docker image
      command: docker push krisvu/regapp:latest
      
# option-2 : creating docker image using docker_image module

#  tasks:
#  - name: building docker image
#    docker_image:
#      build:
#        path: /opt/docker
#      name: simple-devops-image
#     tag: v1
#     source: build
